### ISSUE TITLE
AV port GND required for 12V Step down setups

### ISSUE THREAD

**Issue by fujin** [BrainFPV/TauLabs#11] opened 2015-02-19 07:33 UTC
hi @BrainFPV 

I just hit a weird issue where I didn't have the GND line on the AV port connected (I've been running like this for weeks -- because the ImmersionRC 5G8 didn't seem to need it). I changed my video system to 1G3 which doesn't have an on-board reg like the ImmersionRC Vtx does, so I sent off another 12V line to power that from my 12v/5v BEC.

With the AV GND line disconnected, I was getting constant SENSOR/EVENT alerts and the OSD was jumping off screen in time with the events.

With the GND line connected to the -ve of my filtered 12V step-down, the issue is resolved, OSD stops jumping.

There may be some side-effect from the lack of GND line affecting the sensors. It could be worth looking in to. cc/ @peabody124

**Comment by BrainFPV** [comment] 2015-02-19 13:25
Thanks. What happens is that for some video systems, the DC level of the video signal is too far off from what the Brain can handle, which causes it to detect spurious sync pulses that result in the OSD flickering and the warnings shown in the OSD. I will look into adding a way to discard spurious sync pulses, so it won't be possible to overload the CPU. But this is really a hardware/setup problem and is best resolved with connecting the video GND (as you did).

**Comment by BrainFPV** [comment] 2015-02-19 13:27
My best guess is that the sensor warning is caused because the spurious sync pulses overload the CPU, so there isn't enough time to process the data from the sensor resulting in the warning.

**Comment by fujin** [comment] 2015-02-19 18:59
Cool. That totally makes sense, thanks, and the obviousness of connecting GND was quite plain after going over all of my work :)

**Comment by elafargue** [comment] 2015-02-19 20:30
You should always connect the ground anyway, unless you are willing to destroy your hardware at some point. Without a ground reference between the subsystems, you have a big risk of blowing IO pins. The only situation where you would want to avoid multiple ground connections, is when you might create ground loops...

my 2 cents  :)

**Comment by nuclear12** [comment] 2015-05-14 00:17
I have pretty much the same problem but i'm unable to solve it
my setup:
4s lipo
Current and voltage sensor
castle ccbec for 5v
pololu step-up step-down 12v for camera
if the camera is connected to the osd, i will get sensor warning at the same time as i get the motor beep because it's idle too long
if the camera is not connected, i will only get motor beep when idle
every ground seems to be on the same plane (the av gnd is connected to the same vout gnd of the pololu and the camera)
Thanks for the help

**Comment by peabody124** [comment] 2015-05-14 02:04
@nuclear12 you probably want to message on the @BrainFPV threads to make sure he notices this. 

Edit: ignore me. Got email and didn't realize this **was** the BrainFPV threads!

**Comment by BrainFPV** [comment] 2015-05-17 21:02
@nuclear12 what type of camera are you using? Also, can you post a photo of your setup? So far, whenever this problem occured it was caused by grounding problems.

**Comment by nuclear12** [comment] 2015-05-25 17:26
![spyder](https://cloud.githubusercontent.com/assets/12437243/7800274/f208d024-02e0-11e5-9eda-6c3b4eba9fa6.jpg)
here is a drawing of the circuit (/edit, it's missing a link between the pololu and the cam for the ground in the drawing, sorry)
here is the entire setup
Blackout mini spider
getfpv cs600 camera
immersionrc 5.8ghz 600mw video transmitter
pololu step-up step-down for 12v
castle ccbec 10A for 5v with added cap (10v 4800uf because i tought i was having noise problems)
6x kiss 18 amps esc with added caps (25v 180uf)
6x cobra 2208 2000kv with 645 props
Brainfpv FC
sparkun 180amps current sensor

**Comment by BrainFPV** [comment] 2015-05-26 23:37
@nuclear12 it's not obvious to me what's wrong. Does the problem persist when you unplug the current sensor from the Sen port?

**Comment by nuclear12** [comment] 2015-05-27 02:52
the problem doesn't appear when the osd is not connected
i'll try to disable the battery module (because it doesn't do anything because of the low-voltage when the current is not connected) and have only the osd connected

**Comment by nuclear12** [comment] 2015-06-03 23:34
well sadly, it will have to wait, i've destroyed a cap on my camera and the fc seems to not have any more osd... everything else seems ok

**Closed as completed** 2015-11-23 20:02 UTC
